[package]
name = "torrent-stream"
version = "0.1.0"
authors = ["seb@ukr.net"]

[dependencies]
log = "*"
env_logger = "*"
bytes = "*"
rust-crypto = "*"
futures = "*"
tokio-io = "*"
tokio-core = "*"
tokio-proto = "*"
tokio-service = "*"
rustc-serialize = "*"
byteorder = "*"